### ISSUE TITLE
OTA Upgrade question

### ISSUE THREAD

**Issue by felmue** [m5stack/VAMeter-Firmware#2]
Hello @Forairaaaaa

when I run Settings / OTA Upgrade I am offered V1.0.**3**. However after successful upgrade Settings / About still shows V1.0.**0**.

Am I correct in assuming that the offered version is actually still V1.0.**0** and was only setup to test OTA upgrades?

From the log:
[00:43:19] [I] get info:
 - latestVersion: V1.0.3
 - upgradeAvailable: true
 - firmwareUrl: https://ota-oss.m5stack.com/K136/vameter_user_demo.bin
 - description:
  234234gd hdhd fh hd
 - needUsbFlashing: false

Thanks
Felix

**Comment by Forairaaaaa** [comment]
Hi, currently V1.0.3 on the server is just for OTA testing, a new actual upgrade will be pushed soon, sorry for the misleading~

**Comment by felmue** [comment]
Hello @Forairaaaaa

no worries, that is what I figured. Thank you for confirming.

Thanks
Felix

**Comment by Forairaaaaa** [comment]
Hi, V1.1.3 OTA is pushed now, have a try~

**Comment by felmue** [comment]
Hello @Forairaaaaa 

thank you for the notification. I tired the OTA update to v1.1.3 and it worked like a charm.

Thanks
Felix

**Comment by Forairaaaaa** [comment]
Ur welcome~
